package-lock.json, package.json, src/App.module.css, src/App.tsx, src/ButtonIcon.module.css, src/ButtonIcon.tsx, src/ChatHistory.module.css, src/ChatHistory.tsx, src/DesktopSideBar.tsx, src/MobileSideBar.tsx, src/NavBar.module.css, src/NavBar.tsx, src/setupTests.ts, src/theme/useIsMobileLayout.ts, src/theme/useMediaQuery.ts
- Implement navbar for desktop and mobile layouts
- Placeholder for empty chat history
https://github.com/user-attachments/assets/9c301c7a-dc8d-436c-ae85-db4cfb832123
=> feat: nav bar

src/ChatInput.test.tsx, src/ChatInput.tsx
Adds unit tests for the following
- input is initially focused 
- textarea resizing behavior
- button is disabled until input has length
=> test: ChatInput

src/App.tsx, src/ChatHistory.module.css, src/ChatHistory.tsx, src/ChatHistoryContainer.tsx, src/ChatHistoryItem.module.css, src/ChatHistoryItem.tsx, src/utils/helpers.test.ts, src/utils/helpers.ts
=> feat: mock chat history

src/App.module.css, src/ButtonIcon.module.css, src/ChatHistory.tsx, src/ChatHistoryContainer.tsx, src/ChatHistoryItem.module.css, src/ChatInput.module.css, src/ChatInput.test.tsx, src/ChatInput.tsx, src/ConversationContainer.tsx, src/NavBar.module.css, src/theme/global.css, src/utils/helpers.test.ts, src/utils/helpers.ts
- run prettier
- update mock conversation content
=> fix: run prettier

src/App.tsx, src/ChatInput.test.tsx, src/ChatInput.tsx, src/mocks/conversationHistory.ts, src/utils/helpers.ts
When a user clicks the submit chat button, a user message is pushed onto the active conversation.
https://github.com/user-attachments/assets/d62b8688-74d5-402e-9935-7a46dfa64cef
=> feat: add user message

src/App.tsx, src/ChatHistory.test.tsx, src/ChatHistory.tsx, src/ChatHistoryItem.test.tsx, src/ChatHistoryItem.tsx
https://github.com/user-attachments/assets/6c705903-c9cc-4fd1-a578-130e88d0ccfb
=> feat: edit & delete conversation titles

src/App.tsx, src/NavBar.test.tsx, src/NavBar.tsx, src/useChat.tsx
https://github.com/user-attachments/assets/ef9571a8-ce7d-4404-96e5-f9cc9f21988f
=> feat: new chat button handler

src/ChatInterface.tsx, src/Content.tsx, src/Conversation.test.tsx, src/Conversation.tsx, src/ConversationWrapper.tsx
Passes `onRendered` callback from `ChatInterface` to `Content` component 
https://github.com/user-attachments/assets/6d8cc2c9-328a-4add-a7e9-3936c5a440a5
=> feat: auto scroll as conversation lengthens

src/Conversation.tsx
-  render ellipses animation for streaming
-  add icon for streaming
- removing unneeded syntax
https://github.com/user-attachments/assets/b853ea5d-2904-466a-a4ba-35f66022d9a7
=> fix: streaming UI

src/CancelChatIcon.tsx, src/ChatInput.test.tsx, src/ChatInput.tsx, src/ChatInterface.test.tsx, src/ChatInterface.tsx
https://github.com/user-attachments/assets/38778841-63d6-4122-bf85-e795994b3813
=> feat: implement cancel stream click handler

src/App.tsx, src/DesktopSideBar.tsx, src/MobileSideBar.tsx, src/SideBar.test.tsx, src/SideBar.tsx
currently does nothing, but will soon open the model
=> feat: wire up handler for search history click

package-lock.json, package.json, src/LandingContent.module.css, src/main.tsx
- Implement inter font
- Adjust intro text size & spacing
=> style: implement inter font

src/App.tsx, src/ChatInterface.test.tsx, src/ChatInterface.tsx, src/NavBar.tsx
define handlers to open mobile and desktop menus in parent and pass down callback
=> refactor: navbar click handlers

src/SideBar.test.tsx, src/api/mergeTitleAndMessages.test.ts, src/api/mergeTitleAndMessages.ts, src/types.ts, src/utils/helpers.test.ts
We need the id available on this type so that onClick, we can set the ChatHistory by that id
=> refactor: include id in searchable history type

src/App.module.css, src/Content.module.css
=> style: apply content styles

package-lock.json, src/SearchHistoryModalBody.tsx, src/utils/helpers.test.ts, src/utils/helpers.ts
=> refactor: move highlight function to lib

src/stores/messageHistoryStore/messageHistoryStore.ts, src/toolcalls/chain/prompts.ts, src/useChat.tsx
When calling handleChatCompletion, if there are no existing messages in history, add the system prompt
=> fix: add system prompt to new conversation

package-lock.json, src/App.tsx, src/ChatInterface.test.tsx, src/ChatInterface.tsx, src/ConnectWalletButton.module.css, src/ConnectWalletButton.tsx, src/stores/walletStore/useWalletStore.ts, src/useChat.tsx, src/utils/wallet.ts
Adds a basic connect wallet button
- displays user's address
- updates on switch/disconnect from wallet
https://github.com/user-attachments/assets/be978efb-ab5d-45b4-9bc2-8ccbd40d5f9c
=> feat: connect wallet button

src/ConnectWalletButton.tsx, src/toolcalls/evmBalances.ts, src/toolcalls/evmTransfer.ts, src/toolcalls/helpers/wallet.ts, src/utils/helpers.ts, src/utils/wallet.ts
Pre-organize some of these functions and constants before #109 adds more
=> refactor: split up wallet helpers and utils

src/stores/walletStore/walletStore.test.tsx, src/stores/walletStore/walletStore.ts, src/toolcalls/chain/chainToolCallOperation.ts, src/toolcalls/erc20Conversion.ts, src/toolcalls/evmBalances.ts, src/toolcalls/evmTransfer.ts, src/toolcalls/helpers/wallet.ts, src/types.ts, src/useChat.tsx, src/useExecuteToolCall.tsx
https://github.com/user-attachments/assets/ff6a28bb-e24d-4740-a98d-4b7fe8c23095
=> feat: store wallet type (metamask, hot wallet, etc.)

package-lock.json, src/App.module.css, src/App.tsx
https://github.com/user-attachments/assets/e5894300-3d0f-4a47-bc47-e0cc16a15f80
=> style: project link arrow shows on hover only
